### ISSUE TITLE
配置文件注释为乱码

### ISSUE THREAD

**Issue by muxinxy** [zhyocean/MyBlog#16]
- application.properties
- application-dev.properties
- application-prod.properties

**Comment by javaenigneer** [comment]
具体哪里



---原始邮件---
发件人: "ZengZhe"<notifications@github.com&gt;
发送时间: 2019年12月14日(周六) 中午1:43
收件人: "zhyocean/MyBlog"<MyBlog@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhyocean/MyBlog] 配置文件注释为乱码 (#16)


 
application.properties 

application-dev.properties 

application-prod.properties

**Comment by muxinxy** [comment]
> 具体哪里
> […](#)
> ---原始邮件--- 发件人: "ZengZhe"<notifications@github.com&gt; 发送时间: 2019年12月14日(周六) 中午1:43 收件人: "zhyocean/MyBlog"<MyBlog@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [zhyocean/MyBlog] 配置文件注释为乱码 (#16) application.properties application-dev.properties application-prod.properties — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

所有的汉字都是ASCII码

**Comment by muxinxy** [comment]
比如src/main/resources/application-dev.properties的第一行是### \u672C\u5730\u73AF\u5883

**Comment by zhyocean** [comment]
> 
> 
> 比如src/main/resources/application-dev.properties的第一行是### \u672C\u5730\u73AF\u5883

设置下编译器的编码，properties都设置成utf8

**Comment by muxinxy** [comment]
我自己用在线工具把注释的Unicode编码转换成了中文
