### ISSUE TITLE
我想知道您的短信签名是怎么申请的

### ISSUE THREAD

**Issue by isgangzi** [zhyocean/MyBlog#3]
我想知道您的短信签名是怎么申请的，阿里云申请短信签名那里不是需要上传证书和授权书吗。

**Comment by zhyocean** [comment]
关于申请短信签名需要上传证书和授权书问题，可参考https://www.zhyocean.cn/aboutme页面下方的留言

**Comment by zhyocean** [comment]
关于申请短信签名需要上传证书和授权书问题，可参考[https://www.zhyocean.cn/aboutme](https://www.zhyocean.cn/aboutme)页面下方的留言

**Comment by cdacai** [comment]
嗨，很赞的博客
但是发现了一点小问题，登陆界面报错，注册了登陆不了，应该是哪个库文件没有导入进来
jquery.min.js:2 Uncaught ReferenceError: _ is not defined
    at HTMLDocument.<anonymous> (all.js:184)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
