### ISSUE TITLE
controller和service大部分文件都报这个错是什么原因呀

### ISSUE THREAD

**Issue by zhuxiaoman** [zhyocean/MyBlog#6]
The method setAnswererId(int) is undefined for the type LeaveMessage
![1](https://user-images.githubusercontent.com/39897421/55047828-141da080-5081-11e9-9fab-7f92732df0b9.png)

**Comment by zhuxiaoman** [comment]
虽然有报错，但是可以运行，就是获取不到留言信息、文章什么的

还有我在另一台电脑上没有问题，换了一台电脑后就有问题了，不知道是什么原因

**Comment by zhyocean** [comment]
这个没看懂吖，可以加我QQ一起讨论解决

**Comment by oxidegit** [comment]
你好这个问题解决了吗，我也遇到了
